### ISSUE TITLE
Idea: replace carsonbot with Github actions

### ISSUE THREAD

**Issue by rpkamp** [carsonbot/carsonbot#82]
I don't mean any disrespect with this, I really like carsonbot and what it does, but looking at how far Github actions has come lately I can't help but think it could be nice to implement all the actions there.

Advantages:

- Get a log of everything that happened within the GitHub repository (would solve #14 and also probably #13)
- Removes the need of hosting carsonbot somewhere - less moving parts
- No need to have a server running 24/7 for sporadic actions, so better for the environment
- Leverage actions created by others, such as https://github.com/actions/first-interaction - which would solve #63

Something to think about though would be that GitHub actions doesn't really work well with PHP, because you'd either need to install PHP on their running Ubuntu (takes about a minute) or use a Docker container (which needs to build first, also takes about a minute). So for fast feedback it would be preferred to write actions in NodeJS, which Github Actions can run natively. Since most actions are quite small I don't think that should be a real problem though.

If you think this is something you might be interested in I'd love to take a stab at implementing it :slightly_smiling_face:

**Comment by Nyholm** [comment]
This is an interesting idea. I've been working with automation a fair deal. There is much you can do with github actions and they are super simple to get started with. 

However, using a proper app will give more flexibility and it is easier to hold more advanced logic. Say you want to hold state for instance. 

If a new Carsonbot was built today, one should maybe consider github actions because it is less complex and works for most tasks, but I dont see any reason to "go back" to github actions. 

I vote for closing this.

**Comment by weaverryan** [comment]
Thanks! And, for full disclosure, I don't really care how all of this works - I just want something that does carson's job as easily as possible :).
